<?php
$menURL = $block->escapeHtml($block->getData('men_img'));
$isMenURL = strtolower(substr($menURL, 0, 4)) == 'http' ? true : false;
$menImageURL = $isMenURL ? $menURL : 'pub/media/' . $menURL;

$womenURL = $block->escapeHtml($block->getData('women_img'));
$isWomenURL = strtolower(substr($womenURL, 0, 4)) == 'http' ? true : false;
$womenImageURL = $isWomenURL ? $womenURL : 'pub/media/' . $womenURL;
?>
<div class="container-collection m-5">
    <div class="item-collection banner">
        <a href="<?= $block->escapeHtml(
              $block->getData('men_url')
            ) ?>">
            <img class="img-collection" src='<?= $menImageURL ?>' />
        </a>
        <div class="collection">
            <a href="<?= $block->escapeHtml(
              $block->getData('men_url')
            ) ?>"><?= $block->escapeHtml($block->getData('men_jp')) ?></a>
            <br />
            <a href="<?= $block->escapeHtml(
              $block->getData('men_url')
            ) ?>"><?= $block->escapeHtml($block->getData('men_en')) ?></a>
        </div>
    </div>
    <div class="item-collection banner">
        <a href="<?= $block->escapeHtml(
              $block->getData('women_url')
            ) ?>">
            <img class="img-collection" src='<?= $womenImageURL ?>' />
        </a>
        <div class="collection">
            <a href="<?= $block->escapeHtml(
              $block->getData('women_url')
            ) ?>"><?= $block->escapeHtml($block->getData('women_jp')) ?></a>
            <br />
            <a href="<?= $block->escapeHtml(
              $block->getData('women_url')
            ) ?>"><?= $block->escapeHtml($block->getData('women_en')) ?></a>
        </div>
    </div>
</div>